# Generated by Django 3.0.7 on 2020-06-22 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_currency', to='investments.Currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_currency', to='investments.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='assetpurchase',
            name='transfer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='asset_purchase_transfer', to='investments.Transfer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockexchange',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_exchange_currency', to='investments.Currency'),
        ),
    ]
