# Generated by Django 3.0.7 on 2022-01-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiabolsotransaction',
            name='code',
        ),
    ]
