# Generated by Django 3.0.7 on 2020-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_auto_20200622_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetpurchase',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetpurchase',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='final_value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transfer',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
