# Generated by Django 3.0.7 on 2022-01-14 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_remove_guiabolsotransaction_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiabolsotransaction',
            name='code',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
