# Generated by Django 3.0.7 on 2020-06-22 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20200622_1724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
