# Generated by Django 3.0.7 on 2022-01-15 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_guiabolsocategory_predictable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiabolsotransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_transactions', to='investments.GuiaBolsoCategory'),
        ),
    ]
