# Generated by Django 3.0.7 on 2020-06-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_bank_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='final_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saving',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
