# Generated by Django 3.0.7 on 2020-06-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_auto_20200623_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpurchase',
            name='amount',
            field=models.FloatField(),
        ),
    ]
