# Generated by Django 3.0.7 on 2022-02-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_category_can_invest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('key', 'month', 'year'), name='price history unique'),
        ),
    ]
