# Generated by Django 3.0.7 on 2022-02-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_auto_20220217_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='value',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
