# Generated by Django 3.0.7 on 2022-02-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_pricehistory_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
    ]
