# Generated by Django 3.0.7 on 2022-02-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_auto_20220217_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcache',
            name='url',
            field=models.TextField(unique=True),
        ),
    ]
