# Generated by Django 3.0.7 on 2020-10-11 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0012_auto_20200625_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionsStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options_category', to='investments.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
