# Generated by Django 3.0.7 on 2022-02-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_auto_20220217_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('data', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='UrlCache',
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('key', 'start', 'end'), name='price history unique'),
        ),
    ]
