# Generated by Django 3.0.7 on 2020-10-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_optionsstrategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='fractioned',
            field=models.BooleanField(default=False, verbose_name='Can be fractioned?'),
        ),
    ]
