# Generated by Django 3.0.7 on 2020-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_asset_fractioned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='fractioned',
            field=models.BooleanField(choices=[(True, 'Sim'), (False, 'Não')], default=False, verbose_name='Can be fractioned?'),
        ),
    ]
