# Generated by Django 3.1.7 on 2021-03-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_auto_20201027_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='can_invest',
            field=models.BooleanField(default=True),
        ),
    ]
