# Generated by Django 3.0.7 on 2021-12-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0017_auto_20210311_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_category', to='investments.Category'),
        ),
        migrations.AlterField(
            model_name='assetpurchase',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_asset', to='investments.Asset'),
        ),
    ]
