# Generated by Django 3.0.7 on 2022-01-12 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0018_auto_20211227_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetpurchase',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_purchase_transfer', to='investments.Transfer'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_bank', to='investments.Bank'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_category', to='investments.Category'),
        ),
        migrations.CreateModel(
            name='GuiaBolsoToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiabolso_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='guiabolsotoken',
            constraint=models.UniqueConstraint(fields=('user', 'token'), name='unique token'),
        ),
    ]
