# Generated by Django 3.0.7 on 2022-01-13 02:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0020_auto_20220112_0220'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guiabolsotoken',
            name='unique token',
        ),
        migrations.AddField(
            model_name='guiabolsotoken',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 2, 38, 59, 952550, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guiabolsotoken',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='guiabolsotoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiabolso_token_user', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
