# Generated by Django 3.0.7 on 2022-01-13 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0021_auto_20220113_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaBolsoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=6)),
                ('symbol', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiabolso_category_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
