# Generated by Django 3.0.7 on 2022-01-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0024_guiabolsocategory_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guiabolsocategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='guia bolso category unique'),
        ),
    ]
